feat: improve logging
mangrovedao/reliable-event-subscriber pull request #5
Opened 2023-04-27 13:54 UTC by Louis-Amas

2023-04-27 16:33 UTC, espendk requested changes
lgtm - found small typo

2023-04-27 16:33 UTC, espendk commented on src/blockManager.ts
> +              initializeAt: subscriber.initializedAt,
```suggestion
              initializedAt: subscriber.initializedAt,
```

2023-04-28 07:10 UTC, Louis-Amas commented on src/blockManager.ts
> +              initializeAt: subscriber.initializedAt,
fixed

2023-04-28 07:59 UTC, espendk approved these changes

2023-04-28 08:04 UTC, merged